# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddies',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='buddies',
            field=models.ManyToManyField(blank=True, related_name='_user_buddies_+', to='friends.User'),
        ),
        migrations.DeleteModel(
            name='Buddies',
        ),
    ]
